sets.exported={
    main={ name="Colada", augments={'Enh. Mag. eff. dur. +2','STR+3','"Mag.Atk.Bns."+13','DMG:+5',}},
    sub="Pukulatmuj +1",
    ammo="Pemphredo Tathlum",
    head="Nyame Helm",
    body="Nyame Mail",
    hands="Malignance Gloves",
    legs="Nyame Flanchard",
    feet="Nyame Sollerets",
    neck="Loricate Torque +1",
    waist="Embla Sash",
    left_ear="Sherida Earring",
    right_ear="Malignance Earring",
    left_ring="Shneddick Ring",
    right_ring="Metamor. Ring +1",
    back="Perimede Cape",
}