sets.exported={
    main="Naegling",
    sub="Kaja Rod",
    ammo="Hasty Pinion +1",
    head="Aya. Zucchetto",
    body="Ayanmo Corazza +2",
    hands="Malignance Gloves",
    legs="Aya. Cosciales +2",
    feet="Nyame Sollerets",
    neck="Anu Torque",
    waist="Eschan Stone",
    left_ear="Sherida Earring",
    right_ear="Digni. Earring",
    left_ring="Shneddick Ring",
    right_ring="Metamor. Ring +1",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+10','"Fast Cast"+10','Phys. dmg. taken-10%',}},
}