sets.exported={
    main="Agwu's Axe",
    sub="Sacro Bulwark",
    ammo="Staunch Tathlum +1",
    head="Nuk. Cabasset +2",
    body="Nukumi Gausape +3",
    hands="Nukumi Manoplas +3",
    legs="Nukumi Quijotes +2",
    feet="Nukumi Ocreae +2",
    neck={ name="Bst. Collar +2", augments={'Path: A',}},
    waist="Flume Belt +1",
    left_ear="Tuisto Earring",
    right_ear={ name="Odnowa Earring +1", augments={'Path: A',}},
    left_ring="C. Palug Ring",
    right_ring="Shneddick Ring",
    back={ name="Artio's Mantle", augments={'Eva.+20 /Mag. Eva.+20','Pet: "Regen"+10','Pet: Damage taken -5%',}},
}