sets.exported={
    main="Yagrush",
    sub="Ammurapi Shield",
    ammo="Pemphredo Tathlum",
    head={ name="Nyame Helm", augments={'Path: B',}},
    body="Ebers Bliaut +3",
    hands="Ebers Mitts +3",
    legs="Ebers Pant. +3",
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    neck={ name="Clr. Torque +2", augments={'Path: A',}},
    waist="Rumination Sash",
    left_ear="Etiolation Earring",
    right_ear={ name="Ebers Earring +1", augments={'System: 1 ID: 1676 Val: 0','Accuracy+11','Mag. Acc.+11','Damage taken-3%',}},
    left_ring="Shneddick Ring",
    right_ring="Stikini Ring +1",
    back="Solemnity Cape",
}