sets.exported={
    main={ name="Laevateinn", augments={'Path: A',}},
    sub="Khonsu",
    ammo={ name="Ghastly Tathlum +1", augments={'Path: A',}},
    head="Wicce Petasos +3",
    body="Wicce Coat +3",
    hands="Wicce Gloves +3",
    legs="Wicce Chausses +3",
    feet="Wicce Sabots +3",
    neck={ name="Src. Stole +2", augments={'Path: A',}},
    waist={ name="Acuity Belt +1", augments={'Path: A',}},
    left_ear="Regal Earring",
    right_ear="Etiolation Earring",
    left_ring="Stikini Ring +1",
    right_ring="Shneddick Ring",
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Mag.Atk.Bns."+10','Damage taken-5%',}},
}