sets.exported={
    main="Naegling",
    sub="Blurred Shield +1",
    ammo="Coiste Bodhar",
    head="Sakpata's Helm",
    body="Sakpata's Plate",
    hands="Sakpata's Gauntlets",
    legs="Sakpata's Cuisses",
    feet="Sakpata's Leggings",
    neck={ name="War. Beads +2", augments={'Path: A',}},
    waist="Plat. Mog. Belt",
    left_ear="Infused Earring",
    right_ear="Odnowa Earring +1",
    left_ring="Regal Ring",
    right_ring="Defending Ring",
    back={ name="Cichol's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Damage taken-5%',}},
}