sets.exported={
    main="Yagrush",
    sub="Genmei Shield",
    ammo="Homiliary",
    head={ name="Nyame Helm", augments={'Path: B',}},
    body="Ebers Bliaut +3",
    hands={ name="Nyame Gauntlets", augments={'Path: B',}},
    legs="Ebers Pant. +3",
    feet={ name="Nyame Sollerets", augments={'Path: B',}},
    neck={ name="Clr. Torque +1", augments={'Path: A',}},
    waist="Shinjutsu-no-Obi +1",
    left_ear="Etiolation Earring",
    right_ear={ name="Ebers Earring", augments={'System: 1 ID: 1676 Val: 0','Accuracy+8','Mag. Acc.+8',}},
    left_ring="Defending Ring",
    right_ring="Shneddick Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Phys. dmg. taken-10%',}},
}