sets.exported={
    main="Yagrush",
    sub="Genmei Shield",
    ammo="Homiliary",
    head={ name="Chironic Hat", augments={'"Mag.Atk.Bns."+19','DEX+9','"Refresh"+2','Accuracy+5 Attack+5','Mag. Acc.+5 "Mag.Atk.Bns."+5',}},
    body="Ebers Bliaut +3",
    hands="Nyame Gauntlets",
    legs="Ebers Pant. +3",
    feet="Nyame Sollerets",
    neck={ name="Clr. Torque +1", augments={'Path: A',}},
    waist="Shinjutsu-no-Obi +1",
    left_ear="Etiolation Earring",
    right_ear="Genmei Earring",
    left_ring="Defending Ring",
    right_ring="Shneddick Ring",
    back={ name="Alaunus's Cape", augments={'MND+20','Eva.+20 /Mag. Eva.+20','Phys. dmg. taken-10%',}},
}